[ADD]  Implement starknet_estimateMessageFee method #80
software-mansion/starknet.swift pull request #84
Opened 2023-07-17 11:51 UTC by dnKaratzas

2023-07-17 15:07 UTC, bartekryba requested changes

2023-07-17 15:53 UTC, dnKaratzas commented on Sources/Starknet/Providers/StarknetProvider/JsonRpcParams.swift
> +    let message: StarknetCall
We need to clarify as I tried that already and was getting the following error:

![image](https://github.com/software-mansion/starknet.swift/assets/7944881/fc571894-01c4-4fd8-b917-86f708b87ef5)

Please check https://github.com/starkware-libs/starknet-specs/commit/37c5ed1b5e4608cf8b80b3e06c726aadfa4f0db6
It is tagged for [v0.4.0-rc1](https://github.com/starkware-libs/starknet-specs/releases/tag/v0.4.0-rc1) but they seem to already using that schema

2023-07-18 08:25 UTC, bartekryba commented on Sources/Starknet/Providers/StarknetProvider/JsonRpcParams.swift
> +    let message: StarknetCall
I checked the commit, but it was actually a part of a PR, where it was changed to `MSG_FROM_L1` https://github.com/starkware-libs/starknet-specs/pull/100

2023-07-18 08:40 UTC, dnKaratzas commented on Sources/Starknet/Providers/StarknetProvider/JsonRpcParams.swift
> +    let message: StarknetCall
Fixed 6f9a005646676067dd295add03fdddfe0c39f9f7

2023-07-18 08:49 UTC, bartekryba approved these changes

2023-07-18 10:42 UTC, dnKaratzas commented
Reverted back to 22785ab3d56b9d87f158664c90ad9b8d263d3808
To support `v0.3.1` schema

2023-07-18 10:47 UTC, bartekryba approved these changes

2023-07-18 12:04 UTC, merged